routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use CRA\Http\Controllers\DegreeController;

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['prevent-back-history']],function(){

Route::get('dashboard', 'UserController@dashboard');
Route::get('main_page', 'LoginController@index');
Route::post('main_page/login', 'UserController@login');
Route::post('main_page/logout', 'UserController@logout');
Route::post('main_page/login/permission', 'UserModuleController@loadPermission');
Route::post('{name}/main_page/login/permission', 'UserModuleController@loadPermission');
Route::post('{id}/{name}/main_page/login/permission', 'UserModuleController@loadPermission');
Route::group(['middleware' => ['auth_user']], function () {});

Route::resource('department','DepartmentController');
Route::post('department/save', 'DepartmentController@store');
Route::put('department/edit', 'DepartmentController@update');

Route::resource('building','BuildingController');
Route::post('building/save', 'BuildingController@store');
Route::put('building/edit', 'BuildingController@update');

Route::resource('floor','FloorController');
Route::post('floor/save', 'FloorController@store');
Route::put('floor/edit', 'FloorController@update');

Route::resource('hall','HallController');
Route::post('hall/save', 'HallController@store');
Route::put('hall/edit', 'HallController@update');

Route::resource('class_room','ClassRoomController');
Route::post('class_room/load_floors','ClassRoomController@loadFloors');
Route::post('class_room/load_halls','ClassRoomController@loadHalls');
Route::post('class_room/get_items','ClassRoomController@getItems');
Route::post('class_room/save', 'ClassRoomController@store');
Route::put('class_room/edit', 'ClassRoomController@update');


Route::resource('faculty','FacultyController');
Route::post('faculty/save', 'FacultyController@store');
Route::put('faculty/edit', 'FacultyController@update');

Route::resource('degree','DegreeController');
Route::post('degree/save', 'DegreeController@store');
Route::put('degree/edit', 'DegreeController@update');


Route::resource('batch','BatchController');
Route::post('batch/save', 'BatchController@store');
Route::put('batch/edit', 'BatchController@update');
Route::post('batch/prefix','BatchController@getPrefix');
Route::post('degree/subjects_list','DegreeController@getSubjects');
Route::post('batch/batch_list','BatchController@getSubjectList');



Route::resource('room_allocation','RoomAllocationController');
Route::post('room_allocation/data_find', 'RoomAllocationController@dataFind');
Route::post('room_allocation/room', 'RoomAllocationController@dataRoom');
Route::post('room_allocation/batch', 'RoomAllocationController@dataBatch');
Route::post('room_allocation/facility', 'RoomAllocationController@dataFacility');
Route::post('room_allocation/save', 'RoomAllocationController@save');
Route::put('room_allocation/update', 'RoomAllocationController@update');
Route::get('room_allocation/edit/{id}', 'RoomAllocationController@edit');
Route::post('room_allocation/subject', 'RoomAllocationController@subject');

Route::resource('lecturers','LecturerController');
Route::post('lecturers/save', 'LecturerController@store');
Route::put('lecturers/edit', 'LecturerController@update');

Route::resource('subjects','SubjectController');
Route::post('subjects/save', 'SubjectController@store');
Route::put('subjects/edit', 'SubjectController@update');
Route::get('subjects_list','SubjectController@getSubjectList');

Route::get('room_approval/edit/{id}', 'RoomAllocationApproval@edit');
Route::resource('room_approval','RoomAllocationApproval');
Route::put('room_approval/update', 'RoomAllocationApproval@update');

Route::resource('room_cancel','RoomAllocationCancelController');
Route::get('room_cancel/edit/{id}', 'RoomAllocationCancelController@edit');

Route::resource('exam_allocation','ExamAllocationController');
Route::post('exam_allocation/data_find', 'ExamAllocationController@dataFind');
Route::post('exam_allocation/halls', 'ExamAllocationController@dataHall');
Route::post('exam_allocation/save', 'ExamAllocationController@save');
Route::post('exam_allocation/get_items', 'ExamAllocationController@getItems');
Route::post('exam_allocation/validate_check', 'ExamAllocationController@resValidation');
Route::get('exam_allocation/edit/{id}', 'ExamAllocationController@edit');
Route::put('exam_allocation/update', 'ExamAllocationController@update');

Route::resource('users','UserAuthenticationController');
Route::post('users/save', 'UserAuthenticationController@store');
Route::get('users/edit/{id}', 'UserAuthenticationController@edit');
Route::put('users/update', 'UserAuthenticationController@update');
Route::post('/forgot-password', 'UserAuthenticationController@reset');

Route::resource('users_role','UserRoleController');
Route::post('users_role/save', 'UserRoleController@store');
Route::get('users_role/edit/{id}', 'UserRoleController@edit');
Route::put('users_role/update', 'UserRoleController@update');

Route::resource('user_role_setup','UserRoleSetupController');
Route::post('user_role_setup/save', 'UserRoleSetupController@store');
Route::post('user_role_setup/view', 'UserRoleSetupController@viewPermission');
Route::get('user_role_setup/edit/{id}', 'UserRoleSetupController@edit');
Route::put('user_role_setup/update', 'UserRoleSetupController@update');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('report_view', 'ReportGenerateController@reportView');
//Route::post('report_view/loan','ReportGenerateController@loan');
Route::post('reports/print', 'ReportGenerateController@reportPdf');


Route::resource('lecture_subject','LectureAssignController');
Route::get('lecture_subject/edit/{id}', 'LectureAssignController@edit');
Route::get('lecture_subject/update', 'LectureAssignController@update');

});

app/TransactionTypes.php
<?php

namespace CRA;

use Illuminate\Database\Eloquent\Model;

class TransactionTypes extends Model
{
    //
}

resources/views/transaction/approval/_form.blade.php
{{ csrf_field() }}
<div class="row ">
<div class="col-sm-7 border">
<div class="row ">
    <div class="col-sm-5 ">
        <div class="form-group  mb-sm-0">
            {!! Form::label('id','Request No ',['class'=>'label-info mb-sm-0']) !!}
            @if($button_caption=='Approve')
                {!! Form::text('id', $room_allocation->id,['class'=>'form-control form-control-sm','readonly'=>'true']) !!}
            @else
                {!! Form::text('id', $new_index,['class'=>'form-control form-control-sm text-gray-900','readonly'=>'true']) !!}
            @endif
            @if($errors->has('id'))
                <span class="alert-danger"> {{ $errors->first('id') }}</span>
            @endif
        </div>
    </div>


</div>
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            {!! Form::label('room_id','Class Room',['class'=>'label-info mb-sm-0']) !!}
            {!! Form::text('room_id', $button_caption=='Approve'?$room_allocation->roomId->name:'',['class'=>'form-control form-control-sm text-gray-900 capacity_chk']) !!}

                <span id="span_room_id" class="alert-danger"> {{ $errors->first('room_id') }}</span>

            <input type="hidden" id="h_room_id" name="h_room_id" value="{{$button_caption=='Approve'?$room_allocation->room_id:''}}" />
        </div>
    </div>

    <div class="col-sm-6 btn-toolbar h-25 mt-3" role="toolbar">
        <div class="col-xs-4 col-sm-3 col-md-2 nopad text-center mr-4">
            <label class="image-checkbox chkcl">
                <img class="img-responsive" src="{{url('/image/whiteboard.png')}}"  />
                <input id="whiteboard" type="checkbox" name="facility[]" value="1" />
                <i class="fa fa-check hidden"></i>
            </label>

        </div>
        <div class="col-xs-4 col-sm-3 col-md-2 nopad text-center mr-4">
            <label class="image-checkbox chkcl">
                <img class="img-responsive" src="{{url('/image/projector1.png')}}" />
                <input id="projector" type="checkbox" name="facility[]" value="2" />
                <i class="fa fa-check hidden"></i>
            </label>

        </div>
        <div class="col-xs-4 col-sm-3 col-md-2 nopad text-center mr-4">
            <label class="image-checkbox chkcl">
                <img class="img-responsive" src="{{url('/image/speaker.png')}}" />
                <input id="speaker" type="checkbox" name="facility[]" value="3" />
                <i class="fa fa-check hidden"></i>
            </label>

        </div>
        <div class="col-xs-4 col-sm-3 col-md-2 nopad text-center mr-4">
            <label class="image-checkbox chkcl">
                <img class="img-responsive" src="{{url('/image/internet.png')}}" />
                <input id="internet" type="checkbox" name="facility[]" value="5" />
                <i class="fa fa-check hidden"></i>
            </label>

        </div>
        <div class="col-xs-4 col-sm-3 col-md-2 nopad text-center mr-4">
            <label class="image-checkbox chkcl">
                <img class="img-responsive" src="{{url('/image/wifi.png')}}" />
                <input id="wifi" type="checkbox" name="facility[]" value="4" />
                <i class="fa fa-check hidden"></i>
            </label>

        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-10">
        <div class="form-group">
            {!! Form::label('batch_id','Batch',['class'=>'label-info mb-sm-0']) !!}
            {!! Form::text('batch_id', $button_caption=='Approve'?$room_allocation->batchId->name:'',['class'=>'form-control form-control-sm text-gray-900 capacity_chk']) !!}

                <span id="span_batch_id" class="alert-danger"> {{ $errors->first('batch_id') }}</span>

            <input type="hidden" id="h_batch_id" name="h_batch_id" value="{{$button_caption=='Approve'?$room_allocation->batch_id:''}}"/>
        </div>
    </div>
    <input type="hidden" name="h_batch_cap" id="h_batch_cap"/>
    <input type="hidden" name="h_room_cap" id="h_room_cap"/>
</div>
<div class="row">
    <div class="col-sm-10">
        <div class="form-group">
            {!! Form::label('subject_id','Subject',['class'=>'label-info mb-sm-0']) !!}
            {!! Form::text('subject_id',  $button_caption=='Approve'?$room_allocation->subjectId->name:'',['class'=>'form-control form-control-sm text-gray-900']) !!}

                <span id="span_subject_id"  class="alert-danger"> {{ $errors->first('subject_id') }}</span>
            <input type="hidden" id="h_subject_id" name="h_subject_id" value="{{$button_caption=='Update'?$room_allocation->subject_id:''}}"/>
        </div>
    </div>

</div>
    <div class="border m-2">
    <div class="row ml-2">
        <div class="col-sm-6">
            <div class="form-group">
                <div class="date_from" data-provide="datepicker">
                {!! Form::label('from_date','From Date',['class'=>'label-info mb-sm-0 chg_schedule']) !!}
                {!! Form::text('from_date',$room_allocation->from_date,['class'=>'form-control form-control-sm text-gray-900 chg_schedule']) !!}
                <div class="input-group-addon">
                    <span class="glyphicon glyphicon-th"></span>
                </div>
            </div>
            </div>
        </div>
        <div class="col-sm-6 border-left">
            <div class="form-group">
                <div class="date_to" data-provide="datepicker">
                {!! Form::label('to_date','To Date',['class'=>'label-info mb-sm-0 chg_schedule']) !!}
                {!! Form::text('to_date',$room_allocation->to_date,['class'=>'form-control form-control-sm text-gray-900 chg_schedule']) !!}
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-th"></span>
                    </div>
            </div>
            </div>
        </div>

    </div>
    <div class="row ml-2">
        <div class="col-sm-6">

                <div class="form-group ">
                    <div class='input-group' >
                        {!! Form::label('from_time','From Time',['class'=>'label-info mb-sm-0 ']) !!}
                        {!! Form::time('from_time', $room_allocation->from_time,['class'=>'form-control form-control-sm text-gray-900 time chg_schedule','id'=>'from_time']) !!}
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-time"></span>
                        </div>
                    </div>

        </div>
        </div>


        <div class="col-sm-6 border-left">

            <div class="form-group">
                <div class='input-group' >
                    {!! Form::label('to_time','To Time',['class'=>'label-info mb-sm-0 chg_schedule']) !!}
                    {!! Form::time('to_time', $room_allocation->to_time,['class'=>'form-control form-control-sm text-gray-900 time chg_schedule','id'=>'to_time']) !!}
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </div>
                </div>

            </div>
        </div>
        </div>
    {{--</div>--}}

    {{--</div>--}}
    </div>
   <div class="row p-2">
    <div class="col-sm-12 border">
        <div class="input-group">
            <div class="col-sm-1 ">
            </div>
        <div class="col-sm-2 ">
            <div class='input-group bg-gray-500 text-gray-900' >
            {!! Form::checkbox('mon',$room_allocation->mon,false,['class'=>'form-control form-control-sm text-gray-900',$room_allocation->mon==1?'checked':'','id'=>'mon']) !!}
            {!! Form::label('mon','MON',['class'=>'label-info mb-sm-0']) !!}
            </div>
        </div>
        <div class="col-sm-2 ">
            <div class='input-group bg-gray-500 text-gray-900' >
            {!! Form::checkbox('tue',$room_allocation->tue,false,['class'=>'form-control form-control-sm text-gray-900',$room_allocation->tue==1?'checked':'','id'=>'tue']) !!}
            {!! Form::label('tue','TUE',['class'=>'label-info mb-sm-0']) !!}
            </div>
        </div>
        <div class="col-sm-2 ">
            <div class='input-group bg-gray-500 text-gray-900' >
            {!! Form::checkbox('wed',$room_allocation->wed,false,['class'=>'form-control form-control-sm text-gray-900',$room_allocation->wed==1?'checked':'','id'=>'wed']) !!}
            {!! Form::label('wed','WED',['class'=>'label-info mb-sm-0']) !!}
            </div>
        </div>
        <div class="col-sm-2 ">
            <div class='input-group bg-gray-500 text-gray-900' >
            {!! Form::checkbox('thu',$room_allocation->thu,false,['class'=>'form-control form-control-sm text-gray-900',$room_allocation->thu==1?'checked':'','id'=>'thu']) !!}
            {!! Form::label('thu','THU',['class'=>'label-info mb-sm-0']) !!}
            </div>
        </div>
        <div class="col-sm-2 ">
            <div class='input-group bg-gray-500 text-gray-900' >
            {!! Form::checkbox('fri',$room_allocation->fri,false,['class'=>'form-control form-control-sm text-gray-900',$room_allocation->fri==1?'checked':'','id'=>'fri']) !!}
            {!! Form::label('fri','FRI',['class'=>'label-info mb-sm-0']) !!}
            </div>
        </div>
            <div class="col-sm-1 ">
            </div>
        </div>
    </div>

</div>
    <div class="row p-2">
        <div class="col-sm-12 border">
            <div class="input-group">
                <div class="col-sm-4 ">
                </div>
                <div class="col-sm-2 ">
                    <div class='input-group bg-success text-white' >
                        {!! Form::checkbox('sat',$room_allocation->sat,false,['class'=>'form-control form-control-sm text-gray-900',$room_allocation->sat==1?'checked':'','id'=>'sat']) !!}
                        {!! Form::label('sat','SAT',['class'=>'label-info mb-sm-0']) !!}
                    </div>
                </div>
                <div class="col-sm-2 ">
                    <div class='input-group bg-danger text-white ' >
                        {!! Form::checkbox('sun',$room_allocation->sun,false,['class'=>'form-control form-control-sm text-gray-900',$room_allocation->sun==1?'checked':'','id'=>'sun']) !!}
                        {!! Form::label('sun','SUN',['class'=>'label-info mb-sm-0']) !!}
                    </div>
                </div>
                <div class="col-sm-4 ">
                    <button id="generate" type="button" class="btn btn-sm  btn-info float-right">Generate <i class="fa fa-arrow-alt-circle-right"></i></button>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="col-sm-5">
    <div class="row ">
        <div class="col-sm-12 table-h-300">
            <table class="table-sm  table-bordered table-condensed table-striped" id="tbl_facility"
                   width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>Name</th>
                </tr>
                </thead>
                <tbody>
                    @if(isset($facilities))
                            @foreach($facilities as $list)
                            <tr>
                                <td>{{$list->facilityId->name}}</td>
                            </tr>

                            @endforeach
                    @endif
                </tbody>
            </table>
        </div>

    </div>
    <div class="row">
        <div class="col-sm-12">
            <table name="tbl_schedule" class="table-sm  table-bordered table-condensed table-striped" id="tbl_schedule"
                   width="100%" cellspacing="0">
                <thead>
                <tr class="bg-gray-300">
                    <th>#</th>
                    <th>Date</th>
                    <th>From Time</th>
                    <th>To Time</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @if(isset($schedule))
                    @foreach($schedule as $list)
                        <tr>
                            <td>{{++$i}}</td>
                            <td>{{$list->schedule_date}}</td>
                            <td><input readonly type="time" class="time" id="f_time_{{$i}}" name="f_time_{{$i}}" value="{{$list->from_time}}"></td>
                            <td><input readonly type="time" class="time" id="t_time_{{$i}}" name="t_time_{{$i}}" value="{{$list->to_time}}"></td>
                            <td  class="text-center"><input  type="checkbox" class="" id="chk_{{$i}}" name="chk_{{$i}}" {{$list->leave==0?'checked':''}}></td>
                            <input type="hidden" name="date_{{$i}}" id="date_{{$i}}" value="{{$list->schedule_date}}" />
                        </tr>

                    @endforeach
                @endif

                </tbody>
            </table>
        </div>
        <input type="hidden" name="schedule" id="schedule">
    </div>

</div>

</div>
<div class="float-right mb-2">

    <input type="hidden" id="temp_" name="temp_"  class="text-gray-900"/>
    <button type="button"  id="btnSave" class="btn  btn-success "><i class="fa fa-save"></i>{{$button_caption}}</button>
    <button type="button" class="btn  btn-info"><i class="fa fa-refresh"></i>Reset</button>

</div>

resources/views/transaction/approval/edit.blade.php
@extends('layouts.main')
@section('content')
    {{-- <div class="container">--}}
    <div class="container-fluid">

        <div class="card o-hidden border-0 shadow-lg my-1">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                {!! Form::model($room_allocation, ['url' => ['room_approval/update'],'enctype'=>"multipart/form-data",'method' => 'put','id'=>'room_approval']) !!}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="p-3">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Approval</h1>
                            </div>

                            @include('transaction.approval._form',['button_caption'=>'Approve'])
                            @include('commonForm.searchModel')
                        </div>
                    </div>


                </div>
                {!! Form::close() !!}
            </div>
        </div>

    </div>
@stop

@section('alert')

@stop
@section('application_js')
    {{--<script src="/js/application/batch.js" type="text/javascript"></script>--}}
    <script src="/js/application/room_approve.js" type="text/javascript"></script>

@stop

resources/views/transaction/approval/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="container-fluid">

        {{--editable Page--}}
{{--
        <div class="card-body">

        </div>--}}

        <!-- Page Heading -->
        <h6 class="h4 mb-2 text-gray-800">Class Room Allocation Approval</h6>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="dataTable" class="table-sm table-bordered " id="grid_room_approval" width="100%" cellspacing="0">
                        <thead>
                        <tr class="bg-gray-100">
                            <th class="col-sm-1 ">Request No</th>
                            <th class="col-sm-2 ">Class Room</th>
                            <th class="col-sm-4 ">Batch</th>
                            <th class="col-sm-2 ">From Date</th>
                            <th class="col-sm-2 ">To Date</th>
                            <th class="col-sm-2 ">From Time</th>
                            <th class="col-sm-2 ">To Time</th>
                            <th class="col-sm-1 ">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($room_allocation as $cllist)
                            <tr>
                                <td class="col-md-1">{{$cllist->id}}</td>
                                <td class="col-md-2">{{$cllist->roomId->name}}</td>
                                <td class="col-md-4">{{$cllist->batchId->name}}</td>
                                <td class="col-md-2">{{$cllist->from_date}}</td>
                                <td class="col-md-2">{{$cllist->to_date}}</td>
                                <td class="col-md-2">{{$cllist->from_time}}</td>
                                <td class="col-md-2">{{$cllist->to_time}}</td>
                                <td class="col-md-1">
                                    <a type="button" href="{{route('room_approval.edit',$cllist->id)}}"
                                       class="btn btn-sm btn-warning -edit"><i class="fa fa-edit"></i></a>
                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                    {{--  <div>{{$Clients->links()}}</div>--}}
                </div>
            </div>
        </div>

    </div>
@stop
@section('alert')

@stop
@section('application_js')
    <script src="/js/application/room_allocation.js" type="text/javascript"></script>

@stop