routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use CRA\Http\Controllers\DegreeController;

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['prevent-back-history']],function(){

Route::get('dashboard', 'UserController@dashboard');
Route::get('main_page', 'LoginController@index');
Route::post('main_page/login', 'UserController@login');
Route::post('main_page/logout', 'UserController@logout');
Route::post('main_page/login/permission', 'UserModuleController@loadPermission');
Route::post('{name}/main_page/login/permission', 'UserModuleController@loadPermission');
Route::post('{id}/{name}/main_page/login/permission', 'UserModuleController@loadPermission');
Route::group(['middleware' => ['auth_user']], function () {});

Route::resource('department','DepartmentController');
Route::post('department/save', 'DepartmentController@store');
Route::put('department/edit', 'DepartmentController@update');

Route::resource('building','BuildingController');
Route::post('building/save', 'BuildingController@store');
Route::put('building/edit', 'BuildingController@update');

Route::resource('floor','FloorController');
Route::post('floor/save', 'FloorController@store');
Route::put('floor/edit', 'FloorController@update');

Route::resource('hall','HallController');
Route::post('hall/save', 'HallController@store');
Route::put('hall/edit', 'HallController@update');

Route::resource('class_room','ClassRoomController');
Route::post('class_room/load_floors','ClassRoomController@loadFloors');
Route::post('class_room/load_halls','ClassRoomController@loadHalls');
Route::post('class_room/get_items','ClassRoomController@getItems');
Route::post('class_room/save', 'ClassRoomController@store');
Route::put('class_room/edit', 'ClassRoomController@update');


Route::resource('faculty','FacultyController');
Route::post('faculty/save', 'FacultyController@store');
Route::put('faculty/edit', 'FacultyController@update');

Route::resource('degree','DegreeController');
Route::post('degree/save', 'DegreeController@store');
Route::put('degree/edit', 'DegreeController@update');


Route::resource('batch','BatchController');
Route::post('batch/save', 'BatchController@store');
Route::put('batch/edit', 'BatchController@update');
Route::post('batch/prefix','BatchController@getPrefix');
Route::post('degree/subjects_list','DegreeController@getSubjects');
Route::post('batch/batch_list','BatchController@getSubjectList');



Route::resource('room_allocation','RoomAllocationController');
Route::post('room_allocation/data_find', 'RoomAllocationController@dataFind');
Route::post('room_allocation/room', 'RoomAllocationController@dataRoom');
Route::post('room_allocation/batch', 'RoomAllocationController@dataBatch');
Route::post('room_allocation/facility', 'RoomAllocationController@dataFacility');
Route::post('room_allocation/save', 'RoomAllocationController@save');
Route::put('room_allocation/update', 'RoomAllocationController@update');
Route::get('room_allocation/edit/{id}', 'RoomAllocationController@edit');
Route::post('room_allocation/subject', 'RoomAllocationController@subject');

Route::resource('lecturers','LecturerController');
Route::post('lecturers/save', 'LecturerController@store');
Route::put('lecturers/edit', 'LecturerController@update');

Route::resource('subjects','SubjectController');
Route::post('subjects/save', 'SubjectController@store');
Route::put('subjects/edit', 'SubjectController@update');
Route::get('subjects_list','SubjectController@getSubjectList');

Route::get('room_approval/edit/{id}', 'RoomAllocationApproval@edit');
Route::resource('room_approval','RoomAllocationApproval');
Route::put('room_approval/update', 'RoomAllocationApproval@update');

Route::resource('room_cancel','RoomAllocationCancelController');
Route::get('room_cancel/edit/{id}', 'RoomAllocationCancelController@edit');

Route::resource('exam_allocation','ExamAllocationController');
Route::post('exam_allocation/data_find', 'ExamAllocationController@dataFind');
Route::post('exam_allocation/halls', 'ExamAllocationController@dataHall');
Route::post('exam_allocation/save', 'ExamAllocationController@save');
Route::post('exam_allocation/get_items', 'ExamAllocationController@getItems');
Route::post('exam_allocation/validate_check', 'ExamAllocationController@resValidation');
Route::get('exam_allocation/edit/{id}', 'ExamAllocationController@edit');
Route::put('exam_allocation/update', 'ExamAllocationController@update');

Route::resource('users','UserAuthenticationController');
Route::post('users/save', 'UserAuthenticationController@store');
Route::get('users/edit/{id}', 'UserAuthenticationController@edit');
Route::put('users/update', 'UserAuthenticationController@update');
Route::post('/forgot-password', 'UserAuthenticationController@reset');

Route::resource('users_role','UserRoleController');
Route::post('users_role/save', 'UserRoleController@store');
Route::get('users_role/edit/{id}', 'UserRoleController@edit');
Route::put('users_role/update', 'UserRoleController@update');

Route::resource('user_role_setup','UserRoleSetupController');
Route::post('user_role_setup/save', 'UserRoleSetupController@store');
Route::post('user_role_setup/view', 'UserRoleSetupController@viewPermission');
Route::get('user_role_setup/edit/{id}', 'UserRoleSetupController@edit');
Route::put('user_role_setup/update', 'UserRoleSetupController@update');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('report_view', 'ReportGenerateController@reportView');
//Route::post('report_view/loan','ReportGenerateController@loan');
Route::post('reports/print', 'ReportGenerateController@reportPdf');


Route::resource('lecture_subject','LectureAssignController');
Route::get('lecture_subject/edit/{id}', 'LectureAssignController@edit');
Route::get('lecture_subject/update', 'LectureAssignController@update');

});

app/TransactionTypes.php
<?php

namespace CRA;

use Illuminate\Database\Eloquent\Model;

class TransactionTypes extends Model
{
    //
}

app/Http/Controllers/RoomAllocationController.php
<?php

namespace CRA\Http\Controllers;

use Carbon\Carbon;
use CRA\Batches;
use CRA\BatchSubject;
use CRA\Buildings;
use CRA\ClassFacilities;
use CRA\ClassRooms;
use CRA\ExamAllocationSchedules;
use CRA\RoomAllocation;
use CRA\RoomAllocationSchedule;
use CRA\Subject;
use CRA\Util\ApplicationVarible;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Mockery\Exception;

class RoomAllocationController extends Controller
{
    public function index(){

        $room_allocation = (new RoomAllocation())->with('roomId','batchId')->get();
        $today = date("Y-m-d");
        $buildings = (new Buildings())->pluck('name','id');

        return view('transaction.room_allocation.index', compact('room_allocation','today','buildings'));

    }
    public function dataFind(Request $request){


//        $data = DB::table('room_allocations')
//            ->select(
//                'room_allocations.id',
//                'room_allocations.room_id',
//                'room_allocations.batch_id',
//                'room_allocations.from_date',
//                'room_allocations.to_date',
//                'room_allocations.from_time',
//                'room_allocations.to_time',
//                'room_allocations.status'
//
//            )
//            ->join('class_rooms','class_rooms.id','=','room_allocations.room_id')
//            ->where('room_allocations.from_date','<=',$request->t_date)
//            ->where('room_allocations.to_date','>=',$request->t_date)
//            ->orderBy('class_rooms.id')
//            ->get();

        $data = DB::table('room_allocation_schedules')
            ->select(
                'room_allocations.id',
                'room_allocations.room_id',
                'room_allocations.batch_id',
                'room_allocations.from_date',
                'room_allocations.to_date',
                'room_allocation_schedules.from_time',
                'room_allocation_schedules.to_time',
                'room_allocations.status',
                'batches.name as batch_name',

                DB::raw( 'gradeCalculation(`room_allocation_schedules`.`from_time`) AS grade'),

                DB::raw('IF(
                        `room_allocation_schedules`.`to_time` > "8:30" && gradeCalculation(`room_allocation_schedules`.`from_time`) <= "A",
                        "A",
                        ""
                      ) AS S1'),
                DB::raw('IF(
                        `room_allocation_schedules`.`to_time` > "10:30" && gradeCalculation(`room_allocation_schedules`.`from_time`) <= "B" ,
                        "B",
                        ""
                      ) AS S2'),
                DB::raw('IF(
                        `room_allocation_schedules`.`to_time` > "13:30" && gradeCalculation(`room_allocation_schedules`.`from_time`) <= "C",
                        "C",
                        ""
                      ) AS S3'),
                DB::raw('IF(
                        `room_allocation_schedules`.`to_time` > "15:30" && gradeCalculation(`room_allocation_schedules`.`from_time`) <= "D" ,
                        "D",
                        ""
                      ) AS S4'),

                DB::raw( 'CASE
                   WHEN `room_allocation_schedules`.`to_time` < "10:30" THEN 1
                   WHEN `room_allocation_schedules`.`to_time` < "13:30" && `room_allocation_schedules`.`to_time` >= "10:00" THEN 2
                   WHEN `room_allocation_schedules`.`to_time` < "15:30" && `room_allocation_schedules`.`to_time` >= "13:30" THEN 3
                   WHEN `room_allocation_schedules`.`to_time` < "17:30" && `room_allocation_schedules`.`to_time` >= "15:30" THEN 4
                  END ending')

            )
            ->join('room_allocations','room_allocation_schedules.allocation_id','=','room_allocations.id')
            ->join('class_rooms','class_rooms.id','=','room_allocations.room_id')
            ->join('halls','halls.id','=','class_rooms.hall_id')
            ->join('floors','floors.id','=','halls.floor_id')
            ->join('buildings','buildings.id','=','floors.building_id')
            ->join('batches','batches.id','=','room_allocations.batch_id')
            ->where('room_allocation_schedules.schedule_date','=',$request->t_date)
            ->where('room_allocation_schedules.leave','=',"0")
            ->where('buildings.id','=',$request->building_id)
            ->orderBy('class_rooms.id')
            ->orderBy('room_allocation_schedules.from_time')
            ->get();



        $rooms = DB::table('class_rooms')
            ->select(
                'class_rooms.*'

            )
            ->join('halls','halls.id','=','class_rooms.hall_id')
            ->join('floors','floors.id','=','halls.floor_id')
            ->join('buildings','buildings.id','=','floors.building_id')
            ->where('buildings.id','=',$request->building_id)
            ->orderBy('class_rooms.name')
            ->get();


       return compact('data','rooms');
    }

    public function create(){


        $room_allocation = new RoomAllocation();
        $new_index =(new RoomAllocation())->max('id')+1;

        $batches = (new Batches())->pluck('name','id');

        $transaction_type = ApplicationVarible::$ROOM_ALLOCATION;

        $title = "";
//        $head = ['Name','Type','Capacity','Hall'];
//        $data = ($this->getColumnData());



        return view('transaction.room_allocation.create',compact('room_allocation','new_index','batches','transaction_type','title'));

    }
    function getRoomColumnData($facility){


        $addQry="";
        $add="";
        if(sizeof($facility) > 0){
            foreach ($facility as $key=>$row){

                        $addQry .= ($add." facilities.id=".$row);
                            $add =" AND ";
                    }

            $class_rooms = DB::table('class_rooms')->
                join('class_facilities','class_facilities.class_room_id','=','class_rooms.id')->
                join('facilities','facilities.id','=','class_facilities.facility_id')->
                join('class_types','class_types.id','=','class_rooms.type')->
                join('halls','halls.id','=','class_rooms.hall_id')->
                where('class_rooms.capacity','>','0')->
                whereRaw($addQry)->
                select('class_rooms.*','class_types.name as type','halls.name as hallName')->
                groupBy('class_rooms.id')->
                get();
            $data = [];
            if(sizeof($class_rooms)>0) {
                foreach ($class_rooms as $list) {

                    $data[] =
                        [
                            $list->id,
                            $list->name,
                            $list->type,
                            $list->capacity,
                            $list->hallName

                        ];
                }
            }
        }else{
            $class_rooms = (new ClassRooms())->get();

            $data = [];
            if(sizeof($class_rooms)>0) {
                foreach ($class_rooms as $list) {

                    $data[] =
                        [
                            $list->id,
                            $list->name,
                            $list->types->name,
                            $list->capacity,
                            $list->hallId->name

                        ];
                }
            }

        }

        return $data;

    }

    public function dataRoom(Request $request){

        //dd($request->chk_facility);
        $head[] = ['title'=>'#'];
        $head[] = ['title'=>'Name'];
        $head[] = ['title'=>'Type'];
        $head[] = ['title'=>'Capacity'];
        $head[] = ['title'=>'Hall'];
        $data = ($this->getRoomColumnData(isset($request->chk_facility)?$request->chk_facility:[]));

        $title = "Class Room";



        return compact('head','data','title');
    }

    public function dataBatch(){
        $head[] = ['title'=>'#'];
        $head[] = ['title'=>'Name'];
        $head[] = ['title'=>'Degree'];
        $head[] = ['title'=>'Capacity'];
        $head[] = ['title'=>'Type'];
        $head[] = ['title'=>'Year'];

        $data = ($this->getBatchColumnData());

        $title = "Batch";

        return compact('head','data','title');

    }
    function getBatchColumnData(){

        $batches = (new Batches())->with('degreeId')->get();
        $data = [];

        foreach ($batches as $list){

            $data[] =
                [
                    $list->id,
                    $list->name,
                    $list->degreeId->name,
                    $list->capacity,
                    $list->type,
                    $list->year,


                ];
        }

        return $data;

    }public function subject(Request $request){
        $head[] = ['title'=>'#'];
        $head[] = ['title'=>'Name'];


        $data = ($this->getSubjectColumnData($request->id));

        $title = "Subject";

        return compact('head','data','title');

    }
    function getSubjectColumnData($id){

       // $batches = (new Subject())->where->get();
        $batches = (new BatchSubject())->where('batch_id',$id)->get();

        $data = [];

        foreach ($batches as $list){

            $data[] =
                [
                    $list->subjectId->id,
                    $list->subjectId->name,



                ];
        }

        return $data;

    }

    public function dataFacility(Request $request){


        $facility = (new ClassFacilities())
            ->with('facilityId')
            ->where('class_room_id',$request->id)
            ->get();



        return compact('facility');
    }
//
//    function getRoomColumnData(){
//
//        $data = (new ClassRooms())->get();
//
//        return $data;
//
//    }
//
//    public function dataRoom(){
//
//        $head = ['Name','Type','Capacity','Hall'];
//
//        $data = ($this->getRoomColumnData());
//

resources/views/transaction/room_allocation/create.blade.php
@extends('layouts.main')
@section('content')
    {{-- <div class="container">--}}
    <div class="container-fluid">

        <div class="card o-hidden border-0 shadow-lg my-1">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                {!! Form::model($room_allocation, ['url' => ['room_allocation/save'],'id'=>'room_allocation']) !!}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="p-3">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Room Allocation</h1>
                            </div>

                            @include('transaction.room_allocation._form',['button_caption'=>'Save'])
                            @include('commonForm.searchModel')
                        </div>
                    </div>


                </div>
                {!! Form::close() !!}
            </div>
        </div>

    </div>
@stop

@section('alert')

@stop
@section('application_js')
    {{--<script src="/js/application/batch.js" type="text/javascript"></script>--}}
    <script src="/js/application/room_allocation.js" type="text/javascript"></script>

@stop

resources/views/transaction/room_allocation/edit.blade.php
@extends('layouts.main')
@section('content')
    {{-- <div class="container">--}}
    <div class="container-fluid">

        <div class="card o-hidden border-0 shadow-lg my-1">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                {!! Form::model($room_allocation, ['url' => ['room_allocation/update'],'enctype'=>"multipart/form-data",'method' => 'put','id'=>'room_allocation']) !!}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="p-3">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Edit Room Allocation</h1>
                            </div>

                            @include('transaction.room_allocation._form',['button_caption'=>'Update'])
                            @include('commonForm.searchModel')
                        </div>
                    </div>


                </div>
                {!! Form::close() !!}
            </div>
        </div>

    </div>
@stop

@section('alert')

@stop
@section('application_js')
    {{--<script src="/js/application/batch.js" type="text/javascript"></script>--}}
    <script src="/js/application/room_allocation.js" type="text/javascript"></script>

@stop

resources/views/transaction/room_allocation/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="container-fluid">

        {{--editable Page--}}
{{--
        <div class="card-body">

        </div>--}}

        <!-- Page Heading -->
        <h6 class="h4 mb-2 text-gray-800">Class Room Allocation</h6>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="row">
                    <div class="col-md-1">
                    {!! Form::label('t_date','Date',['class'=>'label-info mb-sm-0']) !!}
                    </div>
                    <div class="col-md-3">
                    <div class="date" data-provide="datepicker">
                        {!! Form::text('t_date',$today,['class'=>'form-control form-control-sm','id'=>'t_date']) !!}
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-th"></span>
                        </div>
                    </div>
                </div>
                    <div class="col-md-1">
                        {!! Form::label('building_id','Filtering',['class'=>'label-info mb-sm-0']) !!}
                    </div>
                    <div class="col-md-4">



                            {!! Form::select('building_id', $buildings,'',['class'=>'form-control form-control-sm','data-live-search'=>'true']) !!}

                        </div>

                    <div class="col-md-3">

                        <a id="btnAddNew" class="btn btn-sm btn-info add-new float-right" href="{{url('room_allocation/create')}}">
                            <i class="fa fa-plus"></i> Add New</a>

                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table-sm table-bordered " id="grid_room" width="100%" cellspacing="0">
                        <thead>
                        <tr class="bg-gray-100">
                            <th class="col-sm-1 ">Class NO</th>
                            <th class="col-sm-2 ">session 1</th>
                            <th class="col-sm-2 ">session 2</th>
                            <th class="col-sm-2 ">session 3</th>
                            <th class="col-sm-2 ">session 4</th>
                        </tr>
                        </thead>
                        <tbody>
                        {{--@foreach($batches as $cllist)--}}
                            {{--<tr>--}}
                                {{--<td class="col-md-1">{{$cllist->id}}</td>--}}
                                {{--<td class="col-md-1">{{$cllist->name}}</td>--}}
                                {{--<td class="col-md-4">{{$cllist->degreeId->name}}</td>--}}
                                {{--<td class="col-md-1">--}}
                                    {{--<a type="button" href="{{route('batch.edit',$cllist->id)}}"--}}
                                       {{--class="btn btn-sm btn-warning -edit"><i class="fa fa-edit"></i></a>--}}
                                {{--</td>--}}
                            {{--</tr>--}}
                        {{--@endforeach--}}

                        </tbody>
                    </table>
                    {{--  <div>{{$Clients->links()}}</div>--}}
                </div>
            </div>
        </div>

    </div>
@stop
@section('alert')

@stop
@section('application_js')
    <script src="/js/application/room_allocation.js" type="text/javascript"></script>

@stop